name: advent-of-code
version: 1.0.0
synopsis: Advent of Code solver
dependencies:
  - base ^>= 4.20
  - bytestring
  - comonad
  - containers
  - directory
  - hspec
  - http-client
  - http-client-tls
  - http-types
  - mtl
  - neat-interpolation
  - parsec
  - text
  - transformers
  - vector

executables:
  advent-of-code:
    main: Main.hs
    source-dirs:
      - app
