[package]
name = "solve"
version = "0.1.0"
authors = ["Noah Luck Easterly <noah.easterly@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt="0.3.21"
regex="1.4.2"
lazy_static="1.4.0"
